CREATE TABLE GRUPOCONTATO (
  cod_grupo INTEGER PRIMARY KEY AUTO_INCREMENT,
  nome_grupo VARCHAR NOT NULL,
  PRIMARY KEY(cod_grupo)
);

CREATE TABLE USUARIO (
  email VARCHAR NOT NULL,
  nome VARCHAR NOT NULL,
  senha VARCHAR NOT NULL,
  data_cont TIMESTAMP NOT NULL,
  PRIMARY KEY(email)
);

CREATE TABLE COMENTARIO (
  cod_comentario INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  USUARIO_email VARCHAR NOT NULL,
  texto VARCHAR NOT NULL,
  PRIMARY KEY(cod_comentario, USUARIO_email),
  INDEX COMENTARIO_FKIndex1(USUARIO_email),
  FOREIGN KEY(USUARIO_email)
    REFERENCES USUARIO(email)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE EVENTO (
  cod_evento INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  USUARIO_email VARCHAR NOT NULL,
  local_evento VARCHAR NOT NULL,
  descricao VARCHAR NULL,
  dt_ini TIMESTAMP NOT NULL,
  dt_fim TIMESTAMP NULL,
  PRIMARY KEY(cod_evento, USUARIO_email),
  INDEX EVENTO_FKIndex1(USUARIO_email),
  FOREIGN KEY(USUARIO_email)
    REFERENCES USUARIO(email)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE GRUPOCONTATO_has_USUARIO (
  GRUPOCONTATO_cod_grupo INTEGER UNSIGNED NOT NULL,
  USUARIO_email VARCHAR NOT NULL,
  PRIMARY KEY(GRUPOCONTATO_cod_grupo, USUARIO_email),
  INDEX GRUPOCONTATO_has_USUARIO_FKIndex1(GRUPOCONTATO_cod_grupo),
  INDEX GRUPOCONTATO_has_USUARIO_FKIndex2(USUARIO_email),
  FOREIGN KEY(GRUPOCONTATO_cod_grupo)
    REFERENCES GRUPOCONTATO(cod_grupo)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(USUARIO_email)
    REFERENCES USUARIO(email)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);


